apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: 'maarten-kafka'
  name: 'knative-serving-people-indexer'
spec:
  template:
    spec:
      containers:
        - image: quay.io/appdev_playground/outbox-pattern-example:dependent-application-indexer-1-0.0.6
          ports:
            - containerPort: 8080